apiVersion: v1
kind: Template
metadata:
  name: dynatrace-easytravel
  labels:
    name: dynatrace-easytravel
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: easytravel-mongodb
    labels:
      app: easytravel-mongodb
  spec:
    selector:
      app: easytravel-mongodb
    template:
      metadata:
        name: easytravel-mongodb
        labels:
          app: easytravel-mongodb
      spec:
        containers:
        - name: easytravel-mongodb
          image: dynatrace/easytravel-mongodb:openshift
          ports:
          - containerPort: 27017
            protocol: TCP
          - containerPort: 28017
            protocol: TCP
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: easytravel-backend
    labels:
      app: easytravel-backend
  spec:
    selector:
      app: easytravel-backend
    template:
      metadata:
        name: easytravel-backend
        labels:
          app: easytravel-backend
      spec:
        containers:
        - name: easytravel-backend
          image: dynatrace/easytravel-backend:openshift
          env:
          - name: ET_DATABASE_LOCATION
            value: easytravel-mongodb:27017
          ports:
          - containerPort: 8080
            protocol: TCP
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: easytravel-frontend
    labels:
      app: easytravel-frontend
  spec:
    selector:
      app: easytravel-frontend
    template:
      metadata:
        name: easytravel-frontend
        labels:
          app: easytravel-frontend
      spec:
        containers:
        - name: easytravel-frontend
          image: dynatrace/easytravel-frontend:openshift
          env:
          - name: ET_BACKEND_URL
            value: http://easytravel-backend:8080
          ports:
          - containerPort: 8080
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: easytravel-mongodb
    labels:
      app: easytravel-mongodb
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: 28017-tcp
      port: 28017
      protocol: TCP
      targetPort: 28017
    selector:
      app: easytravel-mongodb
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: easytravel-backend
    labels:
      app: easytravel-backend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: easytravel-backend
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: easytravel-frontend
    labels:
      app: easytravel-frontend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: easytravel-frontend
    type: ClusterIP
